#+TITLE: Aspekty Prawne Informatyki

#+EMAIL: thisconnected@gmail.com
#+AUTHOR: Patryk Kaniewski

#+CREATOR: PUSB Skierniewice

#+DESCRIPTION: test
#+KEYWORDS:
#+LANGUAGE: pl
#+latex_class: beamer
#+OPTIONS: H:2 toc:nil num:t
#+columns: %45ITEM %10BEAMER_env(Env) %10BEAMER_act(Act) %4BEAMER_col(Col) %8BEAMER_opt(Opt)
#+beamer_theme: Dresden

#+beamer_color_theme: sidebartab
#+beamer_font_theme:
#+beamer_inner_theme:
#+beamer_outer_theme:
#+beamer_header:

* Prawa Autorskie
** Historia Praw Autorskich w Informatyce
Wiekszo praw autorskich (i majtkowych) dotyczcych oprogramowania komputerowego i innych podlegajacych ochronie czsci infromatyki  wywodzi si z prawa "zwykego". W wiekszoci przypadk贸w jest to zdefiniowane lub wzorowane na prawach autorskich utwor贸w literackich.

Opieraja si one gownie na ochronie r贸偶nych form wyra偶enia danego programu.

** Prawa Autorskie w Polsce
*** Prawo autorskie (ustawa z 4 lutego 1994 r), Rodzia 7 (Art 74-77)
- Programy komputerowe podlegaj ochronie jak utwory literackie, o ile przepisy niniejszego rozdziau nie stanowi inaczej.
- Ochrona przyznana programowi komputerowemu obejmuje wszystkie formy jego wyra偶enia. Idee i zasady bdce podstaw jakiegokolwiek elementu programu komputerowego, w tym podstaw czy, nie podlegaj ochronie.
** Prawa Autorskie w Polsce
*** DYREKTYWA PARLAMENTU EUROPEJSKIEGO I RADY 2009/24/WE
W sprawie ochrony prawnej program贸w komputerowych z dnia 23 kwietnia 2009 r.
- ka偶dej formy **wyra偶enia** programu komputerowego, nie za do koncepcji i zasad, na kt贸rych opieraj si programy komputerowe lub wszystkie ich elementy
** Prawa Autorskie na wiecie
*** Digital Millenium Copyright ACT
- Gownie skupia si na bezporedniej i poredniej odpowiedzialnoci platform kt贸re rozprowadzaj treci objte prawem autorskim
*** Patenty na oprogramowanie
Konwencja o udzielaniu patent贸w europejskich zabrania tworzenia takich patent贸w "Program贸w komputerowych"
- Stany Zjednoczone posiadaj ochrone patentow na programy komputerowe

* Prawa wyaczne
** Prawa wyczne
-  trwaego lub czasowego powielania programu lub jego czci
-  translacji, adaptacji, porzdkowania i jakichkolwiek innych modyfikacji programu
-  dystrybucji programu   
** Ograniczenia
- Uprawniony nabywca programu mo偶e powiela, dokonywa translacji, adaptacji lub zmian w programie, jeli jest to konieczne do u偶ycia programu zgodnie z zamierzonym celem
- Osoba majca prawo do u偶ywania programu komputerowego mo偶e sporzdzi kopi zapasow w zakresie, w jakim jest to konieczne do takiego u偶ywania
- Osoba taka mo偶e te偶 obserwowa, bada lub testowa funkcjonowanie programu w celu ustalenia koncepcji i zasad, na kt贸rych opiera si ka偶dy z element贸w programu
** Ograniczenia - Prawa osobiste
   - autorstwa utworu
   - oznaczenia utworu swoim nazwiskiem lub pseudonimem albo do udostpniania go anonimowo
*** Uchylone
   - **nienaruszalnoci treci i formy utworu oraz jego rzetelnego wykorzystania**
   - **decydowania o pierwszym udostpnieniu utworu publicznoci**
   - **nadzoru nad sposobem korzystania z utworu**
** Ograniczenia cd.
*** Uchylone
- wystawa publiczna
- Odstpienie tw贸rcy od umowy ze wzgldu na swoje istotne interesy tw贸rcze
- Tw贸rca mo偶e w zbiorowej publikacji swych utwor贸w umieci utwory, o kt贸rych publikacj zawar odrbn umow

** Digital Rights Management
W og贸lnym znaczeniu amanie jakichkolwiek zabezpiecze anty-pirackich **powinno** by legalne.

Stwarzanie barier dostpu do licencjonwanego lub sprzedawanego oprogramowania jest nielegalne.
*** Pragmatycznie
- Czy DRM pozwala na kontrole dziela po wyjciu z ochrony praw majtkowych?
- Je偶eli zezwolonie s kopie zapasowe, powielanie, adaptacja i zmiany w programie 
** DRM cd.
W 2006 Sony zostao pokonane ws. nielegalnej ochrony praw autorskich (XCP, Media MAX).

*** Art 77^1
Uprawniony mo偶e domaga si od u偶ytkownika programu komputerowego zniszczenia posiadanych przez niego rodk贸w technicznych (w tym program贸w komputerowych), kt贸rych jedynym przeznaczeniem jest uatwianie niedozwolonego usuwania lub obchodzenia technicznych zabezpiecze programu.
** DRM cd.
*** Art. 118^1.
1. Kto wytwarza **urzdzenia** lub ich komponenty przeznaczone do niedozwolonego usuwania lub obchodzenia skutecznych technicznych zabezpiecze przed odtwarzaniem, przegrywaniem lub zwielokrotnianiem utwor贸w lub przedmiot贸w praw pokrewnych albo dokonuje obrotu takimi urzdzeniami lub ich komponentami albo reklamuje je w celu sprzeda偶y lub najmu [...]
2. Kto posiada, przechowuje lub wykorzystuje urzdzenia lub ich komponenty, o kt贸rych mowa ust. 1 [...]

Ta podstawa prawna bya u偶ywana do scigania os贸b przerabiajcych konsole do gier
* Konsekwencje prawa autorskiego na oprogramowaniu
** Wolne oprogramowanie
Wolne oprogramowanie (libre, free software) jest oprogramowaniem rozpowszechnianym na warunkach kt贸re zezwalaja u偶ytkownikom na u偶ywanie oprogramowania w jakimkolwiek celu oraz badanie, zmiany i dystrybucj zmienionych wersji.
** Wolne oprogramowanie cd.
Prawo do badania i modyfikacji wymaga dostpnoci kodu 藕rodowego (lub innego odpowiednika w przypadku innym ni偶 oprogramowanie). Dostp do kodu 藕rodowego nie znaczy ze jakie oprogramowanie jest wolnym oprogramowaniem (przykadem jest Unreal Engine kt贸ry jest licencjonowanym produktem ale mamy wgld do kodu 藕rodowego i mo偶emy wykonywa zmiany jednak dystrybucja jest ograniczona)
** Ruch wolnego oprogramowania
Gownym konsolidacyjnym dziaaniem ruchu wolnego oprogramowania jest zao偶enie Free Software Foundation oraz Projektu GNU przez Richarda Stallmana.
** 4 Wolnoci
- Prawo do u偶ywania oprogramowania w jakimkolwiek celu
- Prawo do badania i modyfikacji
- Prawo do redystrybucji
- Prawo do rozwoju i zmiany publicznej wersji
** Copyleft
Copyleft  jest mechanizmem utrzymywania wolnoci oprogramowania licencjonwanego tak licencja. Gownie skupia sie na zachowaniu licencji (i praw przez ni dawanych) przy redystrybucji oprogramowania.

*** Znane licencje Copyleft
- GNU GPL, LGPL
- FreeBSD
- Mozilla
- Chromium
- Creative Commons (Share-alike)
** Wolne vs Otwarte oprogramowanie
Gown ro偶nica jest u偶ycie licencji copyleft w wolnym oprogramowaniu a u偶ycie sabszej (legalnie) licencji takiej jak np. X11, Apache, MIT
** Dlaczego?
Gownym celemi wolnego (lub otwartego) oprogramowanie s:
- Rozw贸j projekt贸w spoecznoci (linux, gnu, webkit)
- Mo偶liwo wasnego rozwoju projekt贸w
- Bezpieczestwo

* Odpowiedzialno zawodowa
** a
* Bibliografia
- Konwencja o udzielaniu patent贸w europejskich
- Digital Milenium Copyright ACT
- DYREKTYWA PARLAMENTU EUROPEJSKIEGO I RADY 2009/24/WE
- Ustawa o prawie autorskim i prawach pokrewnych
- https://www.chip.pl/2018/10/lamanie-drm-ow-jest-legalne/
- http://prawo.vagla.pl/node/6031
- https://forumprawne.org/prawo-autorskie/152577-lamanie-zabezpieczen-drm.html
- https://www.gnu.org/  
